# Generated by Django 4.0.4 on 2022-07-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomentarios',
            name='comentario_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red.postcomentarios'),
        ),
    ]
