# Generated by Django 4.0.4 on 2022-07-16 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('red', '0003_postcomentarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomentarios',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
