# Generated by Django 4.0.4 on 2022-07-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0004_postcomentarios_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomentarios',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='red.post'),
        ),
    ]
