# Generated by Django 4.0.4 on 2022-07-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0005_alter_postcomentarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomentarios',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red.post'),
        ),
    ]
