# Generated by Django 4.0.4 on 2022-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0006_alter_postcomentarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(default=1, max_length=150, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
