# Generated by Django 4.0.4 on 2022-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
    ]
